#!/usr/bin/perl -w
#
# insertAt: Insert a string or file, at a given place in stdin.
# Written ~2006 by Steven J. DeRose.
#
use strict;
use Getopt::Long;

our %metadata = (
    'title'        => "insertAt.pm",
    'description'  => "Insert a string or file, at a given place in stdin.",
    'rightsHolder' => "Steven J. DeRose",
    'creator'      => "http://viaf.org/viaf/50334488",
    'type'         => "http://purl.org/dc/dcmitype/Software",
    'language'     => "Perl 5.18",
    'created'      => "2006",
    'modified'     => "2021-02-06",
    'publisher'    => "http://github.com/sderose",
    'license'      => "https://creativecommons.org/licenses/by-sa/3.0/"
);
our $VERSION_DATE = $metadata{'modified'};

=pod

=head1 Usage

    insertat [-l line] [-expr 'regex'] [-c column] [-m 'msg'] [-f path] [-q]

Inserts a message or the content of a file, at a certain point in the
input. The point can be a given
line number and column, or the first line matching a given regex.

If neither I<-m> nor I<-f> is given, inserts '<HERE/>'.

This can be use to insert error messages at the lines where they apply,
but remember to do them in reverse order, since inserting them changes
following line numbers.


=head1 Options

=over

=item * B<--column> I<n> OR B<-c>

What column to insert before (default 1 (aka 0)).

=item * B<--edit> OR B<-e>

Open result in your $EDITOR.

=item * B<--file> I<name> OR B<-f>

A file to insert the contents of.

=item * B<--indent> OR B<-i>

Run the *nix C<indent> command on the output (implies I<-e>).
This is mainly designed for indenting C code, but may work ok on
other things, too.

=item * B<--lline> I<n> OR B<-l>

What line to insert at (default 1).

=item * B<--message> I<msg> OR B<-m>

A message string to insert.

=item * B<--newlines> OR B<-n>

Put newlines around the message.

=item * B<--quiet> OR B<-q>
Suppress most messages.

=item * B<--verbose> OR B<-v>
Verbose.

=item * B<--version>

Print version info and exit.

=back


=head1 To do

Perhaps support inserting multiple things in one pass, crossing them off as
it goes along.

Support inserting at all matches, not just first.

Options to insert before/replacing/after the match, like splitAt. Or just
move this functionality in there.


=head1 Related commands

C<splitAt> -- similar but inserts line-breaks.


=head1 Ownership

Copyright 2007, 2018 by Steven J. DeRose.
This work by is licensed under a Creative Commons
Attribution-Share Alike 3.0 Unported License. For further information on
this license, see L<http://creativecommons.org/licenses/by-sa/3.0/>.

For the most recent version, see L<http://www.derose.net/steve/utilities/>.

=cut


###############################################################################
# Options
#
my $doEdit     = 0;
my $expr       = 0;
my $indent     = 0;
my $insertion  = "<HERE/>";
my $newlines   = 0;
my $quiet      = 0;
my $targetline = 1;
my $targetcol  = 1;
my $verbose    = 0;

Getopt::Long::Configure ("ignore_case");
my $result = GetOptions(
	"c|column=i"        => \$targetcol,
	"e|edit!"           => \$doEdit,
	"expr=s"            => \$expr,
	"f|file=s"          => sub { $insertion = `cat $_[1]`; },
	"h|help|?"          => sub { system "perldoc $0"; exit; },
	"i|indent!"         => \$indent,
	"l|line=i"          => \$targetline,
	"m|message=s"       => \$insertion,
	"n|newlines!"       => \$newlines,
	"q|quiet!"          => \$quiet,
	"v|verbose+"        => \$verbose,
    "version"           => sub {
		die "Version of $VERSION_DATE, by Steven J. DeRose.\n";
	}
	);

($result) || die "Bad options.\n";


if ($targetline < 1) {
	warn "Bad -l (line) value '$targetline'.\n";
	system "perldoc $0";
	exit;
}
if ($targetcol < 1) {
	warn "Bad -c (column) value '$targetcol'.\n";
	system "perldoc $0";
	exit;
}

if ($newlines) {
	$insertion = "\n$insertion\n";
	($verbose) && warn "Putting newlines around the message.\n";
}

if ($indent) { $doEdit = 1; }

my $tfile = "";
my $fh;
if ($doEdit) {
	$tfile = "/tmp/insertat_" . int(rand(100000));
    open $fh, ">$tfile";
}
else {
	$fh = "--";
}

# warn "$targetline, $targetcol, '$insertion'.\n";


###############################################################################
#
my $didit = 0;
my $recnum = 0;
while (my $rec = <>) {
    $recnum++;
    if ($recnum == $targetline ||
        (!$didit && $expr && $rec =~ m/$expr/)) {
        vMsg(1, "Inserting at line $recnum.");
        if ($targetcol < length($rec)) {
 		   print $fh substr($rec,0,$targetcol-1)
 		       . $insertion . substr($rec,$targetcol-1);
		}
		else {
 		   print $fh $rec. $insertion;
		}
		$didit = 1;
    }
	else {
		print $fh $rec;
    }
}

($didit) || warn "\nNever reached insertion point, total lines = $recnum.\n";

($quiet) || warn "Inserted '$insertion'.\n";

if ($doEdit) {
	if ($indent) {
		my $tfile2 = "$tfile" . "_indent";
		system "indent $tfile >$tfile2";
		system "mv $tfile2 $tfile";
	}
	system "$ENV{EDITOR} $tfile &";
	system "sleep 5s";
	system "rm $tfile";
}
